// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccess.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260531230000_AddCargo")]
public partial class AddCargo
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        // Target model captured in AppDbContextModelSnapshot.
#pragma warning restore 612, 618
    }
}
